### ISSUE TITLE
Does Lambdanative provide some support for offline operativeness?

### ISSUE THREAD

**Issue by danse** [part-cw/lambdanative#106]
Hello,

With my team at eHealth Africa, we have been working at mobile apps for health in development countries, and one of the most important features for us has been reliable offline operativeness and synchronisation. Since you seem to have used Lambdanative in development countries, you probably hit this issue as well.

So far, our solution relied on [Pouch](https://pouchdb.com/), which we used in a Javascript web app which could eventually be compiled to native. Which support for this use case can we expect to find in Lambdanative?

Cheers

**Comment by mgorges** [comment]
As described in [Development of mHealth Applications for Pre-Eclampsia Triage](http://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=6716019) - Section IV-F "_Data Synchronization_" we use [REDCap](../wiki/Index-of-Module-redcap) to synchronize data between devices. For fields the timestamp is checked and used to overwrite the data on the server or client respectively. @ddunsmuir can probably elaborate more on this?

**Comment by ddunsmuir** [comment]
Thanks @mgorges. Yes, for offline data capture we store data in a local database and then when there is a connection the Internet we have used the API of REDCap ([Research Electronic Data Capture](http://project-redcap.org/)) because this is what is setup at our research institute.

For storing data locally you can use the constant database ([cdb module](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-cdb)) or SQLite ([sqlite module](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-sqlite)).

We have had many projects where survey questions are designed with the online designer in REDCap (by non-technical personal) and then a data dictionary csv file downloaded from REDCap is used as a resource in an app to load field text and details. We have also used the [localization](https://github.com/part-cw/lambdanative/wiki/Index-of-Module-localization) module along with translated versions of the data dictionary for apps to provide multiple languages.

As Matthias mentioned, timestamps are used during synchronization to determine which data is newer, the data on REDCap (originally from another mobile device) or the local device data. There is no built-in feature on REDCap for handling this comparison.

**Comment by danse** [comment]
This answers my question, thanks!
