### ISSUE TITLE
Issue building from v1.0.7/master

### ISSUE THREAD

**Issue by fungiblecog** [part-cw/lambdanative#116]
I can build from the v1.0.6 tag, but v1.0.7, or the latest master gives an error - see attached error output.

[make_output.txt](https://github.com/part-cw/lambdanative/files/342990/make_output.txt)

**Comment by mgorges** [comment]
@fungiblecog - whenever you change gambit versions, which happens when you change from v1.0.6 (which used libgambc 4.7.3) to v1.0.7 or master (both use 4.7.9), you need to scrub the entire build cache. There is code in [make.sh](../blob/master/make.sh) 1535 and below, that should detect this, but this seems to fail in your setting. 

For a start can I ask you to try v1.0.7 or master after you did a `make scrub`, followed by a new `./configure DemoConsole; make` to see if it builds then?  - Thanks!

**Comment by fungiblecog** [comment]
That did the trick, thanks!
