### ISSUE TITLE
How to make the Android Back button work?

### ISSUE THREAD

**Issue by cuspycode** [part-cw/lambdanative#152]
When I run `uSquish` from the Google Play Store, the Back button exits the app. When I compile `uSquish` myself and run it, the Back button has no effect at all. The Back button also has no effect in the versions of the `Calculator`, `DemoHelloWorld`, and `DemoSensors` examples that I have built, but I'm not sure if it's intended or not in those cases. The Home button works in all cases however. So I'd like some advice on how to make the Back button work?

My setup:

ANDROIDAPI=15
ANDROIDARCH=arm
Android SDK version: 24.4.1
Android NDK version: r10e

Emulator used for testing was created with `-t android-15 --abi armeabi-v7a` (Ice Cream).
Hardware device used for testing: Sony Xperia Z3C running Android 6.0.1 (Marshmallow).

I'm a newbie, so I apologize in advance if this may be a generic android question unrelated to lambdanative.

**Comment by mgorges** [comment]
The buttons are defined in [modules/eventloop/eventloop.scm](https://github.com/part-cw/lambdanative/blob/master/modules/eventloop/eventloop.scm). - `EVENT_KEYBACK` is the one you want to write an event handler for, however, I couldn't find an example of its use in this repository. An example of who to do so is `Esc` being used to quits the `DemoHelloWorld` - see [apps/DemoHelloWorld/main.scm#L77](https://github.com/part-cw/lambdanative/blob/master/apps/DemoHelloWorld/main.scm#L77). An older version of RRate had this in its code, which is why it quit upon the back button being pressed:

    (if (and (= t EVENT_KEYPRESS) (= x EVENT_KEYBACK))
      (terminate)
    )

**Comment by cuspycode** [comment]
Thanks for the help! I have now tried adding `((= x EVENT_KEYBACK) (terminate))` to the `cond` expression for key release events in the Calculator app, but there is still no effect when I click on the Back button.

**Comment by mgorges** [comment]
That should do it - could you check if your device sends a different event code by recording the value in [loaders/android/bootstrap.java.in#L232](https://github.com/part-cw/lambdanative/blob/master/loaders/android/bootstrap.java.in#L232), e.g. using `Log.d`?

**Comment by cuspycode** [comment]
I have tried that now, and the correct event code is reported by logcat. But nothing is sent to the event handler in `main.scm`. I tried adding `(#t (terminate))` as the first `cond` clause, and nothing happened when I pressed the Back key. Any key on the calculator keypad caused termination however.

Then I tried detected key press instead of key release. I added `(if (and (= t EVENT_KEYPRESS) (= x EVENT_KEYBACK)) (terminate))` before this line: [Calculator/main.scm#L125](https://github.com/part-cw/lambdanative/blob/master/apps/Calculator/main.scm#L125). That worked. It's a mystery why the Back key release event disappears, but this solution works for me.

**Comment by cuspycode** [comment]
Update: I managed to produce a key release event for the Back key by adding the following code to the `xGLSurfaceView` class in [loaders/android/bootstrap.java.in](/part-cw/lambdanative/blob/master/loaders/android/bootstrap.java.in):

```java
  @Override
  public boolean onKeyUp(int keyCode, KeyEvent event) {
    if (keyCode == KeyEvent.KEYCODE_BACK) {
      queueEvent(new Runnable(){ public void run() {
        renderer.nativeEvent(3,10,0); }});
      return true;
    } else {
        return super.onKeyUp(keyCode, event);
    }
  }
```

**Comment by mgorges** [comment]
Nice job identifying the root cause! All events in [loaders/android/bootstrap.java.in#L220](https://github.com/part-cw/lambdanative/blob/master/loaders/android/bootstrap.java.in#L220) should be `EVENT_KEYPRESS` and not `EVENT_KEYRELEASE`, which makes me wonder why we test for the later in [apps/Calculator/main.scm#L125](https://github.com/part-cw/lambdanative/blob/master/apps/Calculator/main.scm#L125)? - My guess is that we want to allow them to depress a key, move it around if the wrong button was hit and then release on the correct one, upon which we trigger the event. I think your solution of adding this is the best one:

    (if (and (= t EVENT_KEYPRESS) (= x EVENT_KEYBACK)) (terminate))

I'll speak to @clpetersen about whether we want to add your `onKeyUp` hook patch to [loaders/android/bootstrap.java.in](https://github.com/part-cw/lambdanative/blob/master/loaders/android/bootstrap.java.in)

**Comment by cuspycode** [comment]
I think acting on key release is best for the reason you state, and modern Android systems seems to take this approach for the Back button by default. I still don't understand how the key release events are generated and why the Back button is special, but I consider the issue resolved for me now since I can either use key pressed, or patch the java code to get the key release event. Thanks for your assistance @mgorges!

**Comment by ionathanch** [comment]
@mgorges Do we still want to add sending the BACK key event on key-up? Would we want to add sending events for _all_ the keys that we currently handle on key-down to key-up for consistency's sake?

**Comment by mgorges** [comment]
?If we can do so without breaking anything I'd suggest we do it as that would be consistent with other platforms. Thanks!

**Comment by mgorges** [comment]
Sorry if this wasn't clear - I meant implementing the system-wide change.

**Comment by ionathanch** [comment]
Forgot to mention in the commit: c5a10babbe367cd9be6cb7356ffa95e1c9adce05 closes this issue.
