### ISSUE TITLE
Enable screensaver in android

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#187]
All apps build for android will prevent the system from turning off the screen.  Is there an obvious way to disable that feature so that the screensaver works when the app is in the foreground?

I looked in the manifest file but could not find anything related

Best

**Comment by rgh36167** [comment]
On Mon, Apr 23, 2018 at 07:11:21PM +0000, Matthias Görges wrote:
> According to the comment in the line above this: [loaders/android/bootstrap.java.in#L109](https://github.com/part-cw/lambdanative/blob/master/loaders/android/bootstrap.java.in#L109) we disable screen sleeping? 

I noticed it in the source code as well. It could be moved to a module which would activate it only when required but that could possibly cause inconvenience to apps relying on that.

So instead there could be a module doing nothing else than FLAG_KEEP_SCREEN_OFF, or more sophisticated an interface to turn it on/off.

**Comment by karliwalti** [comment]
Thanks for looking into this.

As it is shortly after followed by  @ANDROID_JAVA_ONCREATE@
Would it be sufficient to add  a ANDROID_java_oncreate file in the project that adds the flag. 
Or for backwards compatibility, clear the flag again:
`getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON)`

**Comment by mgorges** [comment]
@karliwalti, before I start fiddling with the default behaviour: Did you try if the clearing the flag using an `ANDROID_java_oncreate` file would work?

**Comment by karliwalti** [comment]
Yes, this works.

**Comment by ionathanch** [comment]
So for this issue, do we want to:
* Document somewhere that the solution would be to add `getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);` to `ANDROID_java_oncreate` in apps or modules that need this functionality; or
* Create a module that can dynamically turn this feature on/off, maybe a `(set-keep-screen-on! keep-screen-on)` function (`keep-screen-on` being a boolean) that interfaces with a function in `ANDROID_java_activityadditions` to either call `addFlags` or `clearFlags` for `FLAG_KEEP_SCREEN_ON`?

The first solution is simpler and assumes the app or module would always want the screen on or always turn off the screen after a while, and the second solution assumes the app or module might want to toggle this feature in the middle of execution. I think if we go for the second solution, we can also extend it to handle other flags, such as the `FLAG_FULLSCREEN` that's currently in `bootstrap.java.in`, so that the new module would be responsible for toggling flags in general, and we can also extend it to other platforms (e.g. seems like [this](https://developer.apple.com/documentation/uikit/uiapplication/1623070-idletimerdisabled) is the equivalent of KEEP_SCREEN_ON for iOS).

**Comment by mgorges** [comment]
For a start documenting it but the other approach might be good to generalize this-not sure if on an extra module or part of lncore?

**Comment by ionathanch** [comment]
I've added some documentation [here](https://github.com/part-cw/lambdanative/wiki/Android-Substitutions#android_java_oncreate) (as well as for other file substitutions since there didn't seem to be any existing documentation on them). IMO there aren't really that many flags and other settings to configure for Android, and they don't seem like things that'd be changed often, so I'm thinking the documentation would be enough?
