### ISSUE TITLE
Redcap import file not efficient

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#193]
The file upload to redcap is quite slow on linux and android platforms (others not tested). Each upload adds 3-5 secs which can sum up if multiple files are to be uploaded.

This is due to the error checking loop at:
https://github.com/part-cw/lambdanative/blob/d43b1d0b12cb03cff3d847529e492204e1b99ebd/modules/redcap/redcap.scm#L578

where httpsclient-recv is called on more time after all message is received

Following code would compromise between efficiency (speed gain > *5) and making sure all error communication is grabbed (it assumes buffer would be filled if there is more to come).

```
(let loop ((n #f))
          (if (and n (> n 0))
              (redcap:data-append! (subu8vector redcap:buf 0 n)))
          (if (and n (fx< n 1000)) ;;stop if one buffer 1024 filled
            (begin
              (httpsclient-close)
              (let ((msg (redcap:split-headerbody (redcap:data->string))))
                (redcap:error-check msg)
              )) 
            (loop (httpsclient-recv redcap:buf))
          ))
```

**Comment by mgorges** [comment]
Don't know how risky this is with respect to yielding incomplete uploads? @nonphatic can have a look.

**Comment by karliwalti** [comment]
I would also have preferred to optimize 

> httpsclient-recv

No risk for the upload, it just might happen with very long error messages that arrive very slowly that they are not fully logged

**Comment by nonphatic** [comment]
@karliwalti As I understand it, the changes you've made here closes the `httpsclient` if the buffer is not filled, meaning that there will be one fewer call to `httpsclient-recv` in most cases, correct? I have a few questions:

- Is there any reason why you're checking for `n < 1000` rather than for, say, 1024 exactly, or `(u8vector-length redcap:buf)`?
- Does the 5x speed improvement occur on removing the unnecessary call to `httpsclient-recv`? Do you mind sharing how you've tested and measured this?
