### ISSUE TITLE
Redcap bugfix xmlstr checkboxes

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#194]
Only first field of selected checkboxes would be prepared for submission
to fix, replace
https://github.com/part-cw/lambdanative/blob/6c56a3b984ae82ddbd87be05bd0c02f5aa31be10/modules/redcap/redcap.scm#L133

with
```
(let loop ((i 0) (str ""))
      (if (= i (length data)) str
  	(loop (+ i 1) 
         (let* ((lpair (list-ref data i))
                (field (car lpair))
                (fieldname (if (string? field) field (symbol->string field)))
                (selections (if (list? lpair) (length (cdr lpair)) 1)))
            (let loop ((p (cdr lpair)) (st str))
             (let* ((val (if (list? p) (car p) p))
                   (value (if (number? val) (number->string val) val))
                    (s (string-append st "<item>"
		    "<record>" record "</record>" 
		      repeat                                                     
		    "<redcap_event_name>" event "</redcap_event_name>"
		    "<field_name>" fieldname "</field_name>"
		    "<value>" value "</value>"
		    "</item>" "\r\n")))
             (if (and (list? p) (> (length p) 1)) (loop (cdr p) s )
               s )))))))
```

**Comment by ddunsmuir** [comment]
The procedure was not setup to take checkboxes as a single inner list. On the app side (outside the module) when you create the data list you would specify values for each individual box. See variable redcap:testrecord1b in [redcap-unittest.scm](https://github.com/part-cw/lambdanative/blob/master/modules/redcap/redcap-unittest.scm#L181) where checks is a checkboxes field.

If we try to use the change suggested by you, I assume the inner list input would be something like:
`(checks "0" "1" "1" "1")`
This doesn't work because the resulting XML would include the same simple fieldname "checks" for each value and then REDCap complains that the field doesn't exist. You need the indices, such as "checks___1". If you want this shortcut for checkboxes, please rewrite the code to set the fieldname properly.

**Comment by karliwalti** [comment]
It was meant to work with

> (checks 0 2 4)  

if box  1 3 and 5 are set

**Comment by ddunsmuir** [comment]
Ah, I was not aware of this shortcut in the XML format. The REDCap API documentation is pretty sparse and the examples don't seem to include checkboxes. I have tested it here and it does work to check the third box by sending:
`<field_name>checks</field_name><value>3</value>`
The indices do start at 1, not 0, so your code above wouldn't work. It would complain that there's no checks____0 field. That's what we came across yesterday.
Please note the limitations of this method in that you cannot use it to uncheck boxes and you are assuming that the boxes you don't want checked are not already checked.
We will revert the revert and add to the unit tests importing this way. The export doesn't need more tests because checkboxes are not exported this way in XML format.

**Comment by nonphatic** [comment]
I've rewritten the inner loop as a `map` + `apply` for clarity (it appears Gambit doesn't implement `fold`) to make it clear that we're adding an item for every element after `checks`:

```
(define (redcap:list->xmlstr record event data . xargs)
  (let* ((instance   (redcap:arg 'instance   xargs #f))
         (instrument (redcap:arg 'instrument xargs #f))
         (repeat (if (and instance instrument) ;;add repeat information if provided
                     (string-append "<redcap_repeat_instrument>" instrument "</redcap_repeat_instrument>"
                                    "<redcap_repeat_instance>" instance "</redcap_repeat_instance>") "")))
    (string-append
      "<?xml version=\"1.0\" encoding=\"UTF-8\" ?>" "\r\n"
      "<records>" "\r\n"
      (let loop ((i 0) (str ""))
        (if (= i (length data)) str
            (loop (+ i 1)
                  (let* ((lpair     (list-ref data i))
                         (field     (car lpair))
                         (fieldname (if (string? field) field (symbol->string field))))
                    (apply string-append str (map
                      (lambda (v)
                        (let ((value (if (number? v) (number->string v) v)))
                          (string-append
                            "<item>"
                            "<record>" record "</record>"
                            repeat
                            "<redcap_event_name>" event "</redcap_event_name>"
                            "<field_name>" fieldname "</field_name>"
                            "<value>" value "</value>"
                            "</item>" "\r\n")))
                      (cdr lpair)))))))
      "</records>"))
)
```

If that looks good, I'll push a commit with the unit test I've added.

**Comment by karliwalti** [comment]
I can check it in the coming days and let you know if it works for us

**Comment by karliwalti** [comment]
@nonphatic  confirming that above code works for us
