### ISSUE TITLE
Java compatibilty

### ISSUE THREAD

**Issue by danielsz** [part-cw/lambdanative#195]
Java 9/10 won't compile Android projects due to deprecation of command line options. (source option)

**Comment by ionathanch** [comment]
Interestingly, just changing
```xml
<property name="java.target" value="1.5" />
<property name="java.source" value="1.5" />
```
to
```xml
<property name="java.target" value="1.6" />
<property name="java.source" value="1.6" />
```
in `/usr/local/android-sdk-*/tools/ant/build.xml` and changing the time-stamping authority of the `jarsigner` step in `lambdanative/targets/android/build-binary` from http://zeitstempel.dfn.de to a different one (http://sha256timestamp.ws.symantec.com/sha256/timestamp and http://timestamp.digicert.com have worked) allows me to compile an Android app successfully with Android SDK Tools 25.2.5 and Java 10 installed on macOS.

@danielsz, were there any specific issues you were running into in regards to command line options?

**Comment by mgorges** [comment]
@ionathanch two questions:
a) Why is there an $ in the echo line that you pipe into ant.properties?
b) What are the terms of use of the new timestamping service you propose we use - DFN is very open that way so we have to use something where the terms are acceptable to any use.

**Comment by ionathanch** [comment]
@mgorges a) It's using [ANSI C-quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html) to escape the newline, since macOS does that automatically but Linux needs an `-e` flag that isn't present on macOS
b) I couldn't find details on the one I proposed in the patch, but I can look into the licences of other TSAs later. Although the reason I'm suggesting a different TSA is that I'm getting this message at the `jarsigner` step:

```
Warning: 
The TSA certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target```

If that can be fixed it wouldn't need to be changed, but I haven't found the cause of this message yet.

**Comment by mgorges** [comment]
@ionathanch okay, so why don't you start with committing the piece about the Java Target/Source being 1.6 and we sort out the TSA later? Certum is only free for non-commercial services.

**Comment by mgorges** [comment]
Since 15efa6d it is possible to specify this in `SETUP`, see [SETUP.template#L11](https://github.com/part-cw/lambdanative/blob/master/SETUP.template#L11). The TSA issue seems to have been resolved since the creation of the issue by the provider?
