### ISSUE TITLE
keyboard signs in Uniforms broken on Mac

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#234]
**Issue:** The UIform keyboards do not display the special function pictures anymore on Mac. Instead there is a white box
**Expected behaviour:** full keyboard with "back" or "enter" sign
**Reproduce:** build DemoUIForms on mac (10.14.3) with latest lambdanative, go to the widget page, select a form field

**Comment by mgorges** [comment]
We have encountered the problem as well - it is also present in some iOS cases and has something to do with low-level OpenGL handling of vertices and transparency _(in glcore.scm)_ which Apple changed. We have not yet been able to identify a solution.

**Comment by mgorges** [comment]
I have created an app to illustrate the problem with clipping? [OpenGLTesting](https://github.com/mgorges/lambdanative-testing/tree/master/apps/OpenGLTesting) - It seems that those textures rendered at runtime are fine, while those shown later are not?

**Comment by mgorges** [comment]
I have narrowed the problem down to a problem with `glGenTextures` in  [ln_glcore/glcore.scm#L395](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glcore/glcore.scm#L395) which sets `u32t=0`, instead of an increasing integer, when un-hiding textures. No idea yet how to solve it though the `glGetError` is empty; potentially something about the OpenGL Context not being active within that thread?

**Comment by peterlew** [comment]
I'm also concerned about it being a thread issue, but haven't found anything to suggest that the OpenGL Context is inactive or different in any way when the later draw is called.

 I tried calling `glGenTextures` for all textures on the first draw, and all the textures were properly assigned increasing `u32t ` ids. Unfortunately, this did not solve the problem. Maybe the unexpected behavior of `glGenTextures` is a side effect instead of a cause of the problem.

**Comment by peterlew** [comment]
It seems that the OpenGL Context could be inactive, and the texture would be marked as initialized anyway. This should be fixed by the commit above.
