### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by saman-pasha** [part-cw/lambdanative#242]
In this code displays "[t]" not localized version
by instructions in docs i guess it should displays 'اتوزی'

main.scm ->
```
   (local-load "config/localization.csv")
   (local-index-set! 2)
   (display (local-get-text "title"))
```

EMBED ->
`!config/localizations.csv`

FONTS ->
`IRANSans.ttf kannada.set 14,24,32 iran`

config/localization.csv ->
`title,OTOZY,[t]`

STRINGS ->
`IRANSans.ttf 24 'اتوزی' title2 Script=kannada`

**Comment by ddunsmuir** [comment]
I setup all the files as you have listed (except I don't have the same .ttf) and I assume you included "localization" or "localization_gui" in your MODULES file. The result for me was an output of:
`[t]`
This is to be expected based on how you set it up. There are a few issues here.

First, I suspect your localization.csv file is not loading since the key of "title" is the fallback when the localization table is not loaded or no row starting with "title" is found. Please check the latest log (in the log folder of your app directory) to see if there's a message like:
`[ERROR] 2019-05-29 09:18:45: localization file /Users/ddunsmuir/Desktop/DemoRedSquare.app/config/localization.csv not found`
Then check that the config folder has been extracted and the localization.csv file is within it in the app directory. Touch the localization.csv file so it has a new modified date. What OS are you running this on? It would be best to use the following cross-platform code:
`(local-load (string-append "config" (system-pathseparator) "localization.csv"))`

Once you get the localization properly loading, it should display [t] in the console. So why does this output [t]? Well, [t] should be used when the use of a font in FONTS does not directly work for the characters that you want, for example when you have two characters that combine together. In this case, it will use a texture, which may be generated from your STRING file. As a texture, this will not work within the console. You cannot use the (display) function to test this. Instead, make sure you are listing "localization_gui" in your MODULES, and use the below code to display it in a label. For example:
`(set! gui (make-glgui))
(glgui-label-local gui 20 20 200 30 "title" iran_24.fnt White)`
(glgui-label-local) dynamically either uses FONTS or STRING depending on whether you have directly specified the text in the localization file or instead put [t] and the matching line in STRING.

When I run your setup with the above change it works except for the first character. This is because that character is outside of the kannada.set. The character, ی has a code of U+06CC. The kannada.set is meant for the Kannada language, used in part of India. I recommend creating a new .set file and placing it in the fonts directory for the language you want. The table [here](https://en.wikipedia.org/wiki/Persian_alphabet) contains the Unicode values you would want to include. You can just edit a .set file in a text editor. Good luck!

**Comment by saman-pasha** [comment]
Thank you ddunsmuir
I hane not change anything in code and the output is still [t]
but I had another problem that you solved it
In docs the in localization_gui the name of label is local-dynamic-label
and when i compiled program it cause segmentation fault
i changed the name as i said to glgui-label-local and the label shows 'اتوزی' as expected
I think ther is a bug in local-get-text that dont take value from STRINGS

**Comment by ddunsmuir** [comment]
Ah, thanks for spotting that mistake on the wiki. I have updated the names of both the functions on that page now.

I think the issue with using FONTS instead of STRINGS, ie. including the text directly within your localization.csv file (as below) is simply due to either the .ttf file or the .set file you are referring to in your FONTS.
`title,OTOZY,اتوزی`
I don't have your .ttf file, and don't know the full Unicode character range you want to support. If I change the localization.csv to the below text, it diplays "hi" just fine:
`title,OTOZY,hi`

Dustin

**Comment by saman-pasha** [comment]
the font is available here https://mianjoo.ir/IRANSans.ttf

When i use
title,OTOZY,اتوزی
local-get-text works correct and glgui-label-local shows nothing

When i use
title,OTOZY,[t]
local-get-text shows [t] and glgui-label-local works correct with value اتوزی

**Comment by ddunsmuir** [comment]
It may be that using FONTS, it won't show the text unless all characters are within the character set you are using. I created a new persian.set file with:
`U+0020-007E`
`U+0600-06FF`
Then I specified this in FONTS:
`IRANSans.ttf persian.set 14,24,32 iran`
The result was no longer blank, but was not ideal, since you will see that each character is rendered separately. For Persian, I recommend using the STRINGS file with [t]. When we use FONTS, all characters in the set are rendered separately and then strung together when needed, but obviously this approach doesn't work for characters that need to connect.

**Comment by saman-pasha** [comment]
Thank you for persian.set
as you said local-get-text does not show right-to-left language's word in correct order
Would you fix it?

**Comment by ddunsmuir** [comment]
I'm not sure I follow. As you said above, I see that when you use STRINGS, glgui-label-local works correct and displays the value of اتوزی. These characters in the correct order. You have to use STRINGS, because FONTS does not combine characters together. Use STRINGS and the [t] in the localization file has the advantage of allowing you to control (per language) the font size and where line breaks occur (include // where you want a line break).

**Comment by saman-pasha** [comment]
OK, got it, it is working
