### ISSUE TITLE
modules/website/website.scm : static page prefered to hook?

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#288]
Ok, this might be a bit picky: in modules/website/website.scm static files are prefered over dynamic generated pages. This is somehow surprising, as you can register a hook and wonder why it is never called. It also gets in your way, when you have a template system - you have to use different names for the templates, you cannot simply use the name of the html file it should deliver. 

Small Example:

index.html:
`<h1>%TITLE%</h1>`

main.scm:
`(define (template-processor var) (string-replace-substring var "%TITLE%" "SOMETHINGBIG"))`
` `
`(website-addhook #f "/index.html"`
`(lambda (args)`
`(string->u8vector (template-processor (u8vector->string `
`(u8vector-decompress (table-ref (website-getdb) "/index_1.html"))))))`

What about changing the precedence in website.scm, so that 
a) dynamic pages are prefered to static pages
b) make the string->u8vector transparent, so that the user can return strings, too.
c) procs for generation of dynamic pages get the stored webpage as a parameter in the argument list,
d) that page should be a string, so that is easier to handle for the user?

Example from above would then be:

`(define (template-processor var) (string-replace-substring var "%TITLE%" "SOMETHINGBIG"))`
` `
`(website-addhook #f "/index.html"`
`(lambda (args page)`
`(template-processor page)))`

**Comment by mgorges** [comment]
Sorry, I can't help with this - the team member who wrote this code is no longer with our group and I don't sufficiently understand it to make this change - as it is not simply changing the order in [modules/website/website.scm#L260](https://github.com/part-cw/lambdanative/blob/master/modules/website/website.scm#L260). Unless if @ddunsmuir has ideas you would either have to provide a pull request, that doesn't break existing apps, or we have to keep it as is.

**Comment by ddunsmuir** [comment]
Will look into it at some point. Sorry, I can't today.

**Comment by zwieblum** [comment]
No problem. Maybe I find time to write it myself. BTW, is there an easier way to send patches than the pull request? I've added a patch to the other issue, but it's closed already: https://github.com/part-cw/lambdanative/issues/287

**Comment by ddunsmuir** [comment]
A pull request is the best option for properly tracking this, so please do that for the other issue.

**Comment by ddunsmuir** [comment]
It would be great, @zwieblum, if you could provide what the pull request would be for this and then I can test it with the existing hybrid apps we have. I would want to make sure it doesn't break or slowdown things.

a) _dynamic pages preferred_ - this would most likely be changing the order around lines [221, 222](https://github.com/part-cw/lambdanative/blob/9926bbc6d09d7555d1ff5be65544ce8bda6551e6/modules/website/website.scm#L221)? It's questionable whether changing that order counts as breaking things. Honestly, if I understand correctly I can't find an example where we use a static page. By that I assume you mean specifying a u8-vector instead of a procedure as the data for a page, the third argument for [(website-addhook)](https://github.com/part-cw/lambdanative/blob/9926bbc6d09d7555d1ff5be65544ce8bda6551e6/modules/website/website.scm#L262). Is this what you mean? We call that argument 'proc' and always specify a procedure, but from line 221 it looks like it doesn't need to be. Why/how do you have both a static page setup and a dynamic with the same document name?

b) _make the string->u8vector transparent_ - [Line 235](https://github.com/part-cw/lambdanative/blob/9926bbc6d09d7555d1ff5be65544ce8bda6551e6/modules/website/website.scm#L235) is ultimately where the u8-vector is used (may be used elsewhere??), so would you suggest users can return a string from their procedure and we check if data is a string here and then convert to u8vector if it is?

c) _procs for generation of dynamic pages get the stored webpage as a parameter in the argument list_ - In your example, the document (page) was index.html, but then you made use of index_1.html. I guess this has to do with your templates? In your example, you are substituting in the content of this other page as the result of the lambda for this page. I'm not quite following that. Where would that content come from? A previous call to website-addhook? Adding another attribute to the call on [line 222](https://github.com/part-cw/lambdanative/blob/9926bbc6d09d7555d1ff5be65544ce8bda6551e6/modules/website/website.scm#L222) will break all the existing code we have, so unless you have a way around this, I don't see that going forward.

d) _that page should be a string_ - This depends on the explanation of c.

**Comment by zwieblum** [comment]
ad b) The content for the substitution comes from the application logic. Just like in this example: [url] https://techtutorialsx.com/2018/10/05/esp32-web-server-template-processing-when-serving-html-from-file-system/[/url] - the ESP8622 uses essentally the same seperation scheme for it's GUI as lambdanative. Line 235 and 236 are affected, but also some more places in (werbsite:servefile).

ad d) from a users point of view strings are easier to handle than u8vector. I think that alost all usters will do u8vector->string->process_the_string->string->u8vector - which generates a lot of repetivive code. But it's a question of taste ;)

ad a & c) these are tightly linked. Yesterday I was playing around a bit with the code and ended up with this possible way:

`(define (website-addhook db document proc)`
`  (table-set! (if db db website:db) (if (procedure? proc (string-append "p:" document) document) proc))`

So procs and pages can live side by side.

in ~ line 219 there would be something like 
`(proc  (table-ref db (string-append "p:" document) #f))`

Then reordering Lines 221 - 223, clean up `zdata`-handling when it's used as as a procedure (which is now handled by `proc`,  seperating the cases where 'proc' is given and `zdata` - or simply appending `zdata` to `cgi-env`). This also makes stings/u8vector conversion transparent - if wanted.

But I've not finished that code yet.

@pull-request: will look into it, but it's a bit out of my workflow. I'm used to submitting patches :)

**Comment by ddunsmuir** [comment]
Ah, ok. I'll have to find some time to go through that tutorial. I think I get the idea now though.

I think there's a problem with your brackets in this:
`
(table-set! (if db db website:db) (if (procedure? proc (string-append "p:" document) document) proc))`
Typically (procedure?) only takes on argument...?

 I look forward to your code.

**Comment by zwieblum** [comment]
Yes, the parantheses is missing. Sorry, this was not copied from my code, just the sketch to show the idea :)

**Comment by zwieblum** [comment]
(just managed to post at the wrong issue)

Ok, this my attempt. Patch applies to modules/website/website.scm. It should not change the behaviour of existing applications. The template - if present - is added to the cgi-env as "U8VECTOR"

Usage example:
(website-addhook #f "/index.html"
(lambda (args)
(cadr (assoc "U8DATA" args))))

Obviousely the last line is where you can do interesting things. IMO more poishing will break compatibility.

Sorry, uploading of files does not work at the moment. This is a link to the patch on my homepage: https://klepp.biz/website-scm.patch

**Comment by zwieblum** [comment]
Ok, upload works again. Here is the patch rename it to website-scm.patch
[website-scm.patch](https://github.com/part-cw/lambdanative/files/4964335/website-scm_patch.txt)

**Comment by zwieblum** [comment]
Has anybody had time to look into this yet?

**Comment by peterlew** [comment]
I'll make this next on my list - thanks for your patience!

**Comment by mgorges** [comment]
I have reformatted your patch but don't understand the `(append cgi-env `(("DATA" ,(u8vector->string (website:decompress zdata)` sufficiently to merge this while ensuring that this won't break something else?

**Comment by zwieblum** [comment]
I have not found any reference to "DATA"  in cgi-env. To be more precise, I have not found any reference to "DATA" in any *.scm-file inside of lambdanative.

**Comment by mgorges** [comment]
Correct, so it this gets never used why do we do this strange construct of expanding on the cgi-env piece?

**Comment by zwieblum** [comment]
To allow things like the simple template engine from over there https://github.com/part-cw/lambdanative/issues/291 to work in an unintrusive way. i.e. keep backward compatibility while giving easy access to the webpage that should be served, e.g.:

[code]
(website-addhook #f "/index.html"
  (lambda (args)
    (let ((data (cadr (assoc "DATA" args))))
      (template-process data))))
      ;data)))
[/code]

**Comment by mgorges** [comment]
Also this seems to segfault to me - if I use the code from your example, `zdata` is a string, not a u8vector?

**Comment by zwieblum** [comment]
Hm ... these are the files with all patches applied to lambdanative/modules/website/website.scm, template module in lambdanative/modules/template and demo application in lambdanative/apps/DemeoWebTemplate. I just retried with a fresh git clone, it workes on Linux. Could you please retry with these changes?

[all.tar.xz](https://github.com/part-cw/lambdanative/files/5065363/all.tar.xz.txt)

**Comment by zwieblum** [comment]
oh, you alredy did it :+1:

**Comment by mgorges** [comment]
Yes, it may have worked with the file before but not with the `(website-addhook #f "/index.html" "<h1>[TEXT]</h1>[PROC]")
` example which made it a string. Anyway, please checkout `master` and see if this works for you. Also note that I merged the template module in to the website, but renamed the functions.
