### ISSUE TITLE
google play issues

### ISSUE THREAD

**Issue by zwieblum** [part-cw/lambdanative#292]
Ok, I ran into 2 issues when trying to publish a lambdanative app on google play:

1) AndroidManifest.xml.in needs the line `<uses-sdk android:targetSdkVersion="28"/>` - otherwise I cannot upload.

2) Google Play now enforces you  to use 32 bit and 64 bit. Workaround: `<uses-sdk android:targetSdkVersion="27"/>` - but this will not allow you install on newer devices (Pie and newer)

Is there a way to persuade lamdanative to build only 64 bit applications? i.e. setting
`APP_ABI=armeabi-v7a` to `APP_ABI=arm64-v8a` failes to compile.

**Comment by zwieblum** [comment]
Ok, amaged to get my testapp published on googleplay. Changes needed:
`<uses-sdk` android:targetSdkVersion="28"/>`

`<uses-sdk android:maxSdkVersion="27"/>`

[https://play.google.com/store/apps/details?id=biz.klepp.dr.caravanmaster](https://play.google.com/store/apps/details?id=biz.klepp.dr.caravanmaster)

**Comment by peterlew** [comment]
Thanks for discovering this and sharing. I'm curious - using this workaround, specifically setting `<uses-sdk android:maxSdkVersion="27"/>`, do you know if installation still works on Pie and newer devices?

It's also worth noting that about a week ago, they upped  the required target version from 28 to 29.

**Comment by zwieblum** [comment]
That#s exactly the problem: You can install the APK on pie and newer devices manually. But google will not allow an installation on devices >= pie over the playstore.

**Comment by peterlew** [comment]
I see - targeting 28 will allow you to publish, but setting max to 27 will stop Play Store installs for 28 or higher. And for some reason, setting max to 27 removes the requirement to use both 32 and 64 bit.

**Comment by zwieblum** [comment]
Yes, that's the trick. But tis excluds quite a number evices already :(

**Comment by peterlew** [comment]
Thank you for helping me understand. I'm looking into whether we can manage any refactoring that would fix this.

**Comment by mgorges** [comment]
The [uses-sdk](https://developer.android.com/guide/topics/manifest/uses-sdk-element) element has three components, minSdkVersion, targetSdkVersion, and maxSdkVersion. We only set the former in [loaders/android/AndroidManifest.xml.in#L7](https://github.com/part-cw/lambdanative/blob/master/loaders/android/AndroidManifest.xml.in#L7), which is set based on the ANDROIDAPI in `SETUP`, but might need to also set the target one.

Building both 32 and 64bit versions, and creating a single 'fat' library might be possible too, as I know we do this for iOS using `lip`, but how to combine two version of android needs to be explored further. https://developer.android.com/distribute/best-practices/develop/64-bit has some steps, however, supporting multiple **ABIs** it may be that this requires us to switch to building with `gradle` instead of `ant`, and as such might be better done in a two-step migration?

**Comment by zwieblum** [comment]
SDL2 for android does build APKs with at least 64+32 bit: https://wiki.libsdl.org/Android

**Comment by mgorges** [comment]
Yes, it is possible, but it is not a straight forward change.

**Comment by zwieblum** [comment]
Definitly. But on the other hand: it's not building a single library for 32+64 bit, it's building 2 libraries in two folders with 2 build runs. I tried to modify the buld system to generate arm64 only, but failed: the assumptions made by the variouse scripts ablut naming conventions of the compiler binaries work for 32 bit, but not for 64 bit.

SDL allows to use cmake or gradle, ant is not supported. But gradle is a PITA to get running :/

**Comment by mgorges** [comment]
Commit 894268f allows you to build 64bit binaries on android, if you set `ANDROIDARCH=arm64` in your `SETUP` file. I believe the minimum API for this is `ANDROIDAPI=21`. Also, you **must** remove the `SYS_PREFIX` in the cache directory, if one exists, so that the toolchain gets rebuild.

**Comment by zwieblum** [comment]
So the workaround for now is: build 32bit APK. Buld 64biz APK. Unpack both. repack one APK with both foldes 32+64 bit ?

**Comment by mgorges** [comment]
I couldn't get that to work manually, but e387cd2 might do this for you? I can't test this as I am still working from home and don't have an Android device available to me.

**Comment by zwieblum** [comment]
This looks nice. 32+64 bit are included in the APK, now I'll need to do some testing to see if the resulting apk actually works.

**Comment by zwieblum** [comment]
I just ran into a problem with yesterdays changes to lambdanative/modules/hybridapp/ANDROID_application_attributes:
'''
[mergemanifest] Manifest merger disabled. Using project manifest only.
     [echo] Handling aidl files...
     [aidl] No AIDL files to compile.
     [echo] ----------
     [echo] Handling RenderScript files...
     [echo] ----------
     [echo] Handling Resources...
     [aapt] Generating resource IDs...
     [aapt] /home/nik/.lambdanative/tmp_build/bin/AndroidManifest.xml:8: error: No resource identifier found for attribute 'usesCleartextTraffic' in package 'android'
     [aapt] 
'''

Removing ../lambdanative/modules/hybridapp/ANDROID_application_attributes lets me build the APK again.

**Comment by mgorges** [comment]
Please don't compound issues; file a separate issue for each problem. 

And yes, we are aware and working on it, as you may have seen from the commit logs - this is another tricky problem which has to do with API levels and newer devices! Unfortunately, this attribute requires API level 23 or higher, however, if it is not set will cause a `Web Page not available: The web page at http://localhost:8080/ could not be loaded because: net::ERR_CLEARTEXT_NOT_PERMITTED` error on newer devices as it defaults to NO; yet at API level 21, which is our new default, it is not defined. - I can't `#ifdef` things so this will require an intervention to the make script...

**Comment by zwieblum** [comment]
Thank you. I installed SDK for API23, now it works for me.

**Comment by mgorges** [comment]
https://android-developers.googleblog.com/2016/04/protecting-against-unintentional.html says that `You don’t have to set minSdkVersion or targetSdkVersion of your app to 23 (Android Marshmallow) to use android:usesCleartextTraffic. On older platforms, this attribute is simply ignored and thus has no effect.`, except for that we can't compile for API 21 unless we remove it?

**Comment by zwieblum** [comment]
Yes, looks like a slight incorrectness in the docs. Most likely all other workarounds will hit the same problem, e.g. Android Network Security Configuration ( https://codelabs.developers.google.com/codelabs/android-network-security-config/index.html#3 / https://developer.android.com/training/articles/security-config#CleartextTrafficPermitted ) - but it might be that a selfsigned certificate for localhost can be added to the apk.

**Comment by mgorges** [comment]
The _Network Security Configuration_ requires API level 24, so ever worse. Self-signed certificates are another set of issues; I am still exploring to simply patch this out if the API is <23.

**Comment by peterlew** [comment]
The compilation error ("No resource identifier found for attribute 'usesCleartextTraffic' in package 'android'") comes during the ant build, so possibly the docs assume use of gradle?

**Comment by mgorges** [comment]
No, but 0807a88 is a hack to make this work.

**Comment by mgorges** [comment]
dc1e9e6 preserves backwards compatibility to only build `arm` if the API is <21; its a terrible hack but it works. This should resolve the original issue, so unless there are others directly related to this, please fill a new issue for them. Thanks also to @peterlew for help in sorting this out.
