### ISSUE TITLE
Nested Widgets question

### ISSUE THREAD

**Issue by charJe** [part-cw/lambdanative#300]
Some widgets like `glgui-dropdownbox` and `glgui-list` only accept runtime rendering functions. Would it be possible to put a `glgui-dropdownbox` inside a `glgui-list`? Maybe a runtime rendered version of `glgui-dropdownbox` and other things like buttons. I found `glgui:dropdownbox-draw` and `glgui:dropdownbox-input` but they seem like functions to help draw the dropdownbox and not meant to be used on their own.

**Comment by mgorges** [comment]
You can put widgets into containers using the [(glgui-container g x y w h)](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/container.scm) feature, as described in [Wiki: glgui-container](https://github.com/part-cw/lambdanative/wiki/glgui-container). However, nesting widgets, instead of making a new purpose-specific widget, seems strange and the input handling would become very complicated. As such I'd suggest you make a new widget, e.g. as [(glgui-chat g x y w h dh lst fnt cb)](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/chat.scm) is a special case of [(glgui-list g x y w h dh lst cb . kcb)](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/list.scm)?

**Comment by charJe** [comment]
Nesting widgets is what other gui tool kits I've looked at use. I noticed that `glgui-chat` doesn't have any inputs; for my specific case, I would like each element of the `glgui-list` to contain a dropdownbox and a timepicker. Would that still be possible?

**Comment by mgorges** [comment]
You can nest widgets, but only some of them, such as I explained with the `glgui-container`. Next, I don't quite understand your first comment - `glgui-chat` includes a list element, which when modified, causes an update the visible content upon the next draw? - See example in [apps/DemoSerial/main.scm#L167](https://github.com/part-cw/lambdanative/blob/4fa37ef4392cc218a86b7dee7813f87797a20320/apps/DemoSerial/main.scm#L167). 

As for the second part of the question the short answer is no; [modules/ln_glgui/dropdownbox.scm#L148](https://github.com/part-cw/lambdanative/blob/4fa37ef4392cc218a86b7dee7813f87797a20320/modules/ln_glgui/dropdownbox.scm#L148) contains a `glgui-list` itself; as such you can't simply change the callback of the `glgui-list` to handle inputs for the `glgui-dropdownbox` inside of it, as the in the modified handler you no longer know which of the nested input handlers (top level or the one inside the dropdownbox) you are in? I really think that for this particular application you need to design a custom widget.

**Comment by charJe** [comment]
Thank you for all the help. I will work on it eventually.

**Comment by mgorges** [comment]
Okay if you come up with something that you can share, please contribute a pull request. Thanks!
