### ISSUE TITLE
Automatically detect changes to android NDK and APIs to clear its cache

### ISSUE THREAD

**Issue by mgorges** [part-cw/lambdanative#315]
Maybe a command that clears the android folder and this file, to be executed when changing ndks or APIs?

_Originally posted by @karliwalti in https://github.com/part-cw/lambdanative/issues/314#issuecomment-690611452_

**Comment by mgorges** [comment]
Yes, but this is not trivial either, as we don't keep track of what the last one was that you used. I have a way to force a world-wide rebuild for everyone (by changing the VERSION), but we'd have to think about this one.

**Comment by mgorges** [comment]
I put an initial piece into b3610b3 which cleans the cache when API or NDK are changed, but am wondering if a better plan would be to have ndk and api specific versions of the arm and arm64 folders? That way one could switch between them as needed, but I have to think more about that idea and how to best implement that.

**Comment by 0-8-15** [comment]
I believe that commit
https://github.com/part-cw/lambdanative/commit/fa18945

would have been much better as it allows to compile for different API versions and NOT scrub the cache each time.

It's actually a very annoying thing to wait for yet another half an hour to rebuild each time when one needs to support for several variants.

Any reason why this was taken out?

**Comment by mgorges** [comment]
Unfortunately, it is not that simple - to make fat libraries for both arm64 and arm, which is not yet known in make.sh where you specify the variant this needs to go into target piece. Also that doesn't fix the issues when switching NDKs that we have been experiencing.

**Comment by 0-8-15** [comment]
I'd like to suggest to not implement automatic cache scrubbing at all.
At least not without a warning and confirmation.

Loosing the cache by accident is a time consuming experience.

**Comment by 0-8-15** [comment]
Can't the SYS_PLATFORM_VARIANT be sub-structured?  That's what it was meant to be used for.

I actually did.  I'm ready to change that code.  But the loss of the feature it a mayor road block to me and needs a fix here one way or another to restore my ability to continue my work.

**Comment by mgorges** [comment]
There are two competing issues, the time it takes to recompile, which I agree is not desirable and which is why I wrote that this needs fixing, and for us needing to troubleshoot other user's problems, when they change APIs and NDKs because things are not internally consistent.

**Comment by 0-8-15** [comment]
Or may I politely as wrt. https://github.com/part-cw/lambdanative/issues/316 to let ` SYS_PLATFORM_VARIANT` lives along until a deprecation period has passed. While general solution is grown.

**Comment by mgorges** [comment]
`c596d78` issues a warning instead, but for the record, I will not spend time troubleshooting other people's problems if they don't do this and experience issues in linking

**Comment by 0-8-15** [comment]
A warning is IMHO not enough!  This begs for trouble.

I all too often just use cursor-up a few times and hit enter.  If this rebuilds the other android API version instead of the one intended, I'm loosing a minute.  If this accidentally clears the cache I loose an hour each time.  I bet I'm lot alone to mistype.

What really bothers me:  We both contributed to the `SYS_PLATFORM_VARIANT`. My workflow and scripts around it depend on it.  The sudden removal of the feature is a major drawback to me.  Especially as it was all but obvious from the log messages that a feature I need was removed.

Right now the `git pull` from three days ago as disrupted me.  I can't any longer test my current work against more that one android version anymore without loosing 10x wall clock with few minutes spread all over those actually watching and doing things.

Not understand did I what you mean by "people's problems if they don't do this and experience issues in linking"? 

For the record:
1. I want to keep the cache.  Preferable the way I'm successfully using the features.  Even two hours once counts for me.  But if I could understand why we have to change this: once I could live with it and rebuild the cache in a different format.  All the time I can't.  Then I'd need to reinvent the wheal.
2. I want to keep a unique cache for the actual variant
3. I want to keep the current behavior until a deprecation period has passed to give me time to move and keep my commitments wrt. my projects.
4. I actually feel that developers are users too and fail to double check every keystroke before the finger actually hits the key.
5. I'd tend to suggest that the `configure` script in the project directory is extended to split the optional `platform` on optional `-` signs and use the first of the optional components as the API version in case of the `android` target.  This would be compatible with the other use cases I have in mind.  No problem here to discuss these details first.

**Comment by mgorges** [comment]
I realize it was a huge mistake of me to accept your pull request for `SYS_PLATFORM_VARIANT` in the past and I apologize for that; I hadn't considered the influence of the change for future expansions such as the recent addition of arm64, which we need to go to the Google Play store. Adding `SYS_PLATFORM_VARIANT` makes duplicate toolchains (which are very large and take a while to create), which only depend on API and architecture, but with that change exist for each API level. Rather, there should be a single `android` folder, with single instances of toolchains, and multiple **android-arch-api** (or **android-ndk-arch-api**) variants in it.

**Comment by 0-8-15** [comment]
> I realize it was a huge mistake of me to accept your pull request for `SYS_PLATFORM_VARIANT` in the past and I apologize for that; I hadn't considered the influence of the change for future expansions such as the recent addition of arm64, which we need to go to the Google Play store.

I'm not blaming anybody for not knowing things.  Let alone remembering everything anytime.

> Adding `SYS_PLATFORM_VARIANT` makes duplicate toolchains (which are very large and take a while to create), which only depend on API and architecture, but with that change exist for each API level.

Well, it's not exactly `SYS_PLATFORM_VARIANT` itself; this just adds a *configurable* feature to distinguish variants.

The duplicate toolchains are a drawback of the implementation so far.

Which could be improved upon.  (As I did, but not enough as to bother you with a pull request.) Without entirely removing it without even a warning.

If it had been removed with an explicit commit messages as to (as many as applicable):

- "the damage being done at all"
- the reasons it was bad in the first place
- the conflicts with those "recent additions"
- maybe hints how to map the discontinued feature the new behavior
- an deprecation period please

I'd not be that disappointed with the current situation as I am.

I'd still appreciate to learn about the details.

> Rather, there should be a single **android** folder, with single instances of toolchains, and multiple **arch-api** (or **ndk-arch-api**) variants in it.

I'd enjoy to discuss how things *should* be done.  And in this case I feel I'd start from the opposite assumption.

Right now, however, I consider to set up multiple virtual machines each holding a full lambdanative devopment environment and just mounting the source code and *cache*`/packages` directory into the same place everywhere in order to not argue anymore why I feel it would be a good idea to keep the cache even if this creates multiple copies of the toolchain.  I'd like to address the latter too, but why copy it into the cache in the first place?  Multiple VMs are a solution much worse in terms of disk space, but usable.  Cache flushes each edit-compile-test-edit cycles are not.

That's what's going to hold me back form further discussions here until solved.

May I ask you to clarify how to proceed: a) keep the feature for a while to give me time to replace it with the things added more recently (which I'd prefer as it would allow me still pull from master)  or b) leave it out for me to install multiple VM's once my *stick-with-the-old-thing-for-daily-use* period passed?

**Comment by mgorges** [comment]
_Neither_ - I'd rather fix the problem in a way that doesn't require the cache to be cleared but allows parallel APIs to be used now. While it might require some adjustments to your workflow, mostly depending on what other things you hacked locally that we don't know about, it should enable better future adjustments, which will have to come when we eventually replace **ant** for **gradle**. 
If you look at b0d98c3, I did reintroduce `SYS_PLATFORM_VARIANT` but it is applied later in [make.sh#L987](https://github.com/part-cw/lambdanative/blob/master/make.sh#L987) so that it only affects the target-specific pieces. Also you can't override it as it gets set dynamically in [targets/android/_host_macosx#L52](https://github.com/part-cw/lambdanative/blob/master/targets/android/_host_macosx#L52) instead of coming out of `make.sh`. When combined with 01d94cb you can now do things like this:
`./configure DemoRedSquare android-19; make; ./configure DemoRedSquare android; make` which for me builds both an android (arm-only) version of DemoRedSquare for API=19, as well as a arm+arm64 version for API=21 in a single line

**Comment by mgorges** [comment]
I believe this is resolved, if not @0-8-15 and @karliwalti please comment and reopen.
