### ISSUE TITLE
scheme compiling issues new warnings

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#333]
Some recent updates (last two weeks) cause a compiler warning in linux (ubuntu LTS20.04) 

```
 => compiling scheme payload..
    /home/walterk/SoftwareRepo/lambdanative/modules/download/download.scm ..
*** WARNING -- "unless" is not defined,
***            referenced in: ("/home/walterk/.cache/lambdanative/linux/build/3948996557.c")
*** WARNING -- "when" is not defined,
***            referenced in: ("/home/walterk/.cache/lambdanative/linux/build/3948996557.c")
```
It is likely in `libraries/libgamc/gambc-v4_7_9/lib/syntax-case.scm`

I have not yet observed a direct consequence on code execution...

**Comment by mgorges** [comment]
No, this was introduced in b219dca by @0-8-15. They are used in `glgui-chat`, specifically [modules/ln_glgui/chat.scm#L249](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/chat.scm#L249) and [modules/ln_glgui/chat.scm#L255](https://github.com/part-cw/lambdanative/blob/master/modules/ln_glgui/chat.scm#L255). I guess this was introduced in Gambit versions 4.9.3, specifically commit https://github.com/gambit/gambit/commit/584c8b2c40efe7111242bc72d6f84b1abaae3cd4 in January of 2019. Thus, if you use `libgambc` instead of `libgambit` in [modules/config/LIBRARIES#L1](https://github.com/part-cw/lambdanative/blob/master/modules/config/LIBRARIES#L1), it is not available and as such we get the warning.

**Comment by mgorges** [comment]
I think this blocks #330, which uses `when` in line 311 of the patch.
