### ISSUE TITLE
Download libgd from main repository

### ISSUE THREAD

**Issue by bkmgit** [part-cw/lambdanative#451]
Libgd is downloaded from the LambdaNative website.  It is better to obtain it from the main repository https://github.com/libgd/libgd

**Comment by mgorges** [comment]
e4054e4 says: "Version from https://github.com/libgd/libgd/archive/gd-2.1.1.tar.gz doesn't ship configure script, and requires bootstrapping or the use of autoreconf -f -i. This requires a lot of Perl packages and hinders easy build on CYGWIN. Until fixed by upstream we'll self-host it.". However, this version link you propose has the same hash so it is identical and should work.
