### ISSUE TITLE
how to use the system default keyboard

### ISSUE THREAD

**Issue by pkvov** [part-cw/lambdanative#47]
Android and IOS has their own keyboard to input non English characters, such as Chinese and Arabic.
It is very important to let the user use the Input method that they installed (Android platform)

**Comment by clpetersen** [comment]
Just a few notes to follow up on this topic: Please note that key design choice behind lambdanative is portability. That's why the individual platform loaders are minimal, and we have a common visual framework that looks/runs/feels the same on all platforms. The advantage is that the same code base works on all platforms, and the disadvantage is that you do not have access to native widgets.

In many cases you can work around the widget limitations. We have deployed successfully deployed applications in quite diverse languages, such as Kannada, Sindhi and Portuguese.  However, if you are looking to develop a fullblown unicode iOS/Android text editor for example, then lambdanative is probably not the right tool for the job. 

In any case, it should be possible to add native keyboard support. On Android my understanding is that it would require extending the loader to have an invisible edittext field. A resultreceiver can then collect the key presses and send them on to scheme in the usual way. As @mgorges noted, we would welcome an implementation in the form of a pull request, as long as it does not break current functionality.

**Comment by pkvov** [comment]
is there a plugin system like Apache Cordova, to allow people access the native widgets or apis

**Comment by mgorges** [comment]
The native APIs are available through JNI for Android, and potentially Objective-C for iOS. An example of these binding usage can be found in the [serial](../blob/master/modules/serial) or [gps](../blob/master/modules/gps) module source code. There currently is no native widget support but we would welcome support/contributions in this respect.

**Comment by mgorges** [comment]
My initial attempt at this can be found in 70f8ff4. Please expand as needed and reopen when you have a pull request with enhancements.
