### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by qingniaotonghua** [part-cw/lambdanative#59]
When I start the demoapp DemoCube, there is an error:
==> Starting application..
targets/macosx/install: line 53: 41336 Segmentation fault: 11  /Users/王玮/Desktop/DemoCubeTest.app/DemoCubeTest
wangweideMacBook-Pro:lambdanative-master wangwei$

the code result in this error may be:
(set! box (glgui-box-dragable gui 0 0 100 100 Red box-callback))
      (glgui-widget-set! gui box 'draw-handle #f)

When I comment these two lines codes,the app can start normally.

In fact, some orther demoapp also exist similar problem like DemoHelloWorld，DemoMultitouch..

**Comment by mgorges** [comment]
I don't know about DemoHelloWorld but both DemoMultiTouch and DemoCube had a bug, which was fixed in b17ffce: `box` is a build-in function of gambit, which ab9d874 exposed. Could you pleae pull, recompile and report back? Also please check if DemoHelloWorld really segfaults, as that may be an unrelated issue. Thanks.

**Comment by mgorges** [comment]
Were you able to confirm that this problem no longer exists for you? If yes, please close this issue.

**Comment by qingniaotonghua** [comment]
Thanks a lot，^_^

**Comment by qingniaotonghua** [comment]
I have update the my local lambdanative..
