### ISSUE TITLE
Files not visible in Android MTP USB connection

### ISSUE THREAD

**Issue by karliwalti** [part-cw/lambdanative#95]
Files created within lambdanative are not visible through the media transfer protocol connection between and Android device and an USB connected PC.  E.g. filed from wave and trend output, csv module. This is the case until the device reboots or an app with system admin app is scanning the whole sdcard.
The issue can be solved by running the mediascanner on the files/folders created:
http://developer.android.com/reference/android/media/MediaScannerConnection.html

Not clear if it is better to run the mediascanner on each call of close-output-port (would probably need a redefinition for Android) or when terminating the app on the entire set of app subfolders.
 Any opinion  on what approach to take?

**Comment by mgorges** [comment]
For a start I'd suggest to add it to the `scheduler` module, as `PLUGINS` currently don't support `ANDROID_*` additions. Could you try this patch to see if it captures all required files? - It might need to be expanded to recursively walk through the folders in order to identify subfolders, or work as is.

```
diff --git a/modules/scheduler/ANDROID_java_imports b/modules/scheduler/ANDROID_java_imports
new file mode 100644
index 0000000..defb36c
--- /dev/null
+++ b/modules/scheduler/ANDROID_java_imports
@@ -0,0 +1 @@
+import android.media.MediaScannerConnection;
diff --git a/modules/scheduler/ANDROID_java_ondestroy b/modules/scheduler/ANDROID_java_ondestroy
new file mode 100644
index 0000000..a2c1104
--- /dev/null
+++ b/modules/scheduler/ANDROID_java_ondestroy
@@ -0,0 +1,2 @@
+MediaScannerConnection.scanFile(this, new String[]{"/sdcard/@SYS_APPNAME@/results",
+  "/sdcard/@SYS_APPNAME@/log","/sdcard/@SYS_APPNAME@/config"}, null, null);
```

**Comment by karliwalti** [comment]
Sorry, for writing not earlier. We are currently testing this , but it seems not to work entirely. We are still investigating the reasons, but it could be related to different versions of Android.
We will submit an updated patch hopefully soon

**Comment by mgorges** [comment]
f902fac should now get called that 448d8d4 is in place. Please test again and otherwise file a patch - Thanks!

**Comment by karliwalti** [comment]
Can't confirm that onDestroy gets called. Still looking into why this is, but could be that Android only selectively chooses to run these 
We consider creating a seperate module so it can be called on demand.

**Comment by mgorges** [comment]
Try moving the Mediascanner to `onStop()` or `onPause()`? According to the documentation, you can't rely on running things in `onDestoy`.

**Comment by clpetersen** [comment]
Have you made any progress on this?

**Comment by mgorges** [comment]
Commit d43b1d0 adds `(android-run-mediascanner)`, which you could try to use to run the media scanner at a different time than closing the application.

**Comment by ionathanch** [comment]
Commit ff1ea21e97338c81e03cc6ba46562d93449ebcbc fixes the problem of files not being scanned because scanFile won't scan the actual files inside directories. According to [this](https://www.grokkingandroid.com/adding-files-to-androids-media-library-using-the-mediascanner/) (as well as some testing of my own), the actual scanning runs asynchronously, so I've added a callback to set a flag when the scanning has finished in commit 7a076ce7e59d8c5c8ca894786d505cc6caa3a873. The existing code had called `(android-run-mediascanner)` in onDestroy, which could cause a problem even when it _is_ being run: because we return immediately, there might not have been enough time for the MediaScanner to connect and scan before the activity is terminated; the call has been removed in commit ef60a4ee7aff4e78bf19e45d484fcfdc322d21e3. 

To solve the problem of calling MediaScanner on closing the app, I originally called `finish-and-terminate` right in `c-mediascanner-callback` (which is called by `MediaScannerConnection.OnScanCompletedListener`), but this caused Android to think that the app had crashed. In the end the following code worked:

```scheme
(define (terminate)
  (let ((finish-and-terminate (lambda ()
          (if app:android? (android-finish))
          (if (procedure? hook:terminate) (hook:terminate)))))
    (if app:android? (begin
      (android-run-mediascanner)
      (let loop ()
        (if (not android-mediascanner-done?) (begin (thread-sleep! 0.01) (loop))))))
    (finish-and-terminate))
)
```

But this caused a lag between pressing the Close button on, say, PhoneOx, and the app actually closing, because MediaScanner does take a noticeable amount of time to run (a few hundred milliseconds, according to the article I linked). 

The app becomes no longer visible after `onPause`, so I tried putting a `Thread.sleep()` loop in `onStop` to check for MediaScanner being done, but since `finish()` returns right away and we call `exit(0)` after that, there's no time to reach the other Activity callbacks (`onStop`, `onDestroy`).

Not every app (or even just every app that uses the `scheduler` module) writes files out, so maybe we should just call `(android-run-mediascanner)` and wait for the flag to be set only when it's really needed instead of on every app termination, and `onStop` and `onDestroy` not being called is a separate issue from this one. `(android-run-mediascanner)` definitely works now, anyway.

**Comment by ionathanch** [comment]
N.B. On older versions of Android (e.g. KitKat/4.4), the files may show up in `/storage/emulated/legacy` rather than `/sdcard`, despite `/sdcard` being a soft link to the former. It also seems like this MTP issue has been around for [six](https://issuetracker.google.com/issues/36956498) [years](https://issuetracker.google.com/issues/37071807).
